DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS breakages;
-- DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS position_data;
-- DROP TABLE IF EXISTS sensors_data;
-- DROP TABLE IF EXISTS wheels;
-- DROP TABLE IF EXISTS cars;
-- DROP TABLE IF EXISTS refresh_store;
-- DROP TABLE IF EXISTS users;
-- DROP EXTENSION "uuid-ossp";