// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package rest

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthorizationScopes = "Authorization.Scopes"
)

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ReportResponse defines model for ReportResponse.
type ReportResponse = []byte

// SensorData defines model for SensorData.
type SensorData struct {
	Pressure    *float32 `json:"pressure,omitempty"`
	Temperature *float32 `json:"temperature,omitempty"`
	Time        *string  `json:"time,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

// UpdatePassword defines model for UpdatePassword.
type UpdatePassword struct {
	NewPassword string `json:"newPassword"`
}

// UserDetails defines model for UserDetails.
type UserDetails struct {
	Email      *string `json:"email,omitempty"`
	FirstName  *string `json:"firstName,omitempty"`
	Inn        *string `json:"inn,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	MiddleName *string `json:"middleName,omitempty"`
	Password   *string `json:"password,omitempty"`
	Phone      *string `json:"phone,omitempty"`
	TimeZone   *string `json:"timeZone,omitempty"`
}

// UserRegistration defines model for UserRegistration.
type UserRegistration struct {
	Email      string  `json:"email"`
	FirstName  string  `json:"firstName"`
	Inn        *string `json:"inn,omitempty"`
	LastName   string  `json:"lastName"`
	MiddleName *string `json:"middleName,omitempty"`
	Password   string  `json:"password"`
	Phone      string  `json:"phone"`
	TimeZone   *string `json:"timeZone,omitempty"`
}

// VehicleRegistration defines model for VehicleRegistration.
type VehicleRegistration struct {
	AxleCount    int    `json:"axleCount"`
	Brand        string `json:"brand"`
	CompanyInn   string `json:"companyInn"`
	DeviceId     string `json:"deviceId"`
	LicensePlate string `json:"licensePlate"`
	UniqueId     string `json:"uniqueId"`
	VehicleType  string `json:"vehicleType"`
}

// VehicleResponse defines model for VehicleResponse.
type VehicleResponse struct {
	AxleCount    *int    `json:"axleCount,omitempty"`
	Brand        *string `json:"brand,omitempty"`
	CompanyInn   *string `json:"companyInn,omitempty"`
	DeviceId     *string `json:"deviceId,omitempty"`
	Id           *string `json:"id,omitempty"`
	LicensePlate *string `json:"licensePlate,omitempty"`
	UniqueId     *string `json:"uniqueId,omitempty"`
	VehicleType  *string `json:"vehicleType,omitempty"`
}

// WheelRegistration defines model for WheelRegistration.
type WheelRegistration struct {
	AxleNumber     int     `json:"axleNumber"`
	MaxPressure    float32 `json:"maxPressure"`
	MaxTemperature float32 `json:"maxTemperature"`
	Mileage        float32 `json:"mileage"`
	MinPressure    float32 `json:"minPressure"`
	MinTemperature float32 `json:"minTemperature"`
	SensorNumber   string  `json:"sensorNumber"`
	TireBrand      string  `json:"tireBrand"`
	TireCost       float32 `json:"tireCost"`
	TireModel      string  `json:"tireModel"`
	TireSize       string  `json:"tireSize"`
	VehicleId      string  `json:"vehicleId"`
	WheelPosition  int     `json:"wheelPosition"`
}

// WheelResponse defines model for WheelResponse.
type WheelResponse struct {
	AxleNumber     *int     `json:"axleNumber,omitempty"`
	Id             *string  `json:"id,omitempty"`
	MaxPressure    *float32 `json:"maxPressure,omitempty"`
	MaxTemperature *float32 `json:"maxTemperature,omitempty"`
	Mileage        *float32 `json:"mileage,omitempty"`
	MinPressure    *float32 `json:"minPressure,omitempty"`
	MinTemperature *float32 `json:"minTemperature,omitempty"`
	SensorNumber   *string  `json:"sensorNumber,omitempty"`
	TireBrand      *string  `json:"tireBrand,omitempty"`
	TireCost       *float32 `json:"tireCost,omitempty"`
	TireModel      *string  `json:"tireModel,omitempty"`
	TireSize       *string  `json:"tireSize,omitempty"`
	VehicleId      *string  `json:"vehicleId,omitempty"`
	WheelPosition  *int     `json:"wheelPosition,omitempty"`
}

// GetReportParams defines parameters for GetReport.
type GetReportParams struct {
	UserId string `form:"userId" json:"userId"`
}

// GetSensorParams defines parameters for GetSensor.
type GetSensorParams struct {
	WheelId string `form:"wheelId" json:"wheelId"`
}

// PostAutoJSONRequestBody defines body for PostAuto for application/json ContentType.
type PostAutoJSONRequestBody = VehicleRegistration

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = UserRegistration

// PutUserJSONRequestBody defines body for PutUser for application/json ContentType.
type PutUserJSONRequestBody = UpdatePassword

// PostWheelsJSONRequestBody defines body for PostWheels for application/json ContentType.
type PostWheelsJSONRequestBody = WheelRegistration

// PutWheelsJSONRequestBody defines body for PutWheels for application/json ContentType.
type PutWheelsJSONRequestBody = WheelRegistration

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a vehicle
	// (POST /auto)
	PostAuto(w http.ResponseWriter, r *http.Request)
	// User login
	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)
	// Refresh access token
	// (POST /refresh)
	PostRefresh(w http.ResponseWriter, r *http.Request)
	// Generate report
	// (GET /report)
	GetReport(w http.ResponseWriter, r *http.Request, params GetReportParams)
	// Get sensor data
	// (GET /sensor)
	GetSensor(w http.ResponseWriter, r *http.Request, params GetSensorParams)
	// User registration
	// (POST /user)
	PostUser(w http.ResponseWriter, r *http.Request)
	// Update user password
	// (PUT /user)
	PutUser(w http.ResponseWriter, r *http.Request)
	// Get user details
	// (GET /user/{id})
	GetUserId(w http.ResponseWriter, r *http.Request, id string)
	// Register a wheel
	// (POST /wheels)
	PostWheels(w http.ResponseWriter, r *http.Request)
	// Update wheel data
	// (PUT /wheels)
	PutWheels(w http.ResponseWriter, r *http.Request)
	// Get wheel data
	// (GET /wheels/{id})
	GetWheelsId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register a vehicle
// (POST /auto)
func (_ Unimplemented) PostAuto(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User login
// (POST /login)
func (_ Unimplemented) PostLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh access token
// (POST /refresh)
func (_ Unimplemented) PostRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate report
// (GET /report)
func (_ Unimplemented) GetReport(w http.ResponseWriter, r *http.Request, params GetReportParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get sensor data
// (GET /sensor)
func (_ Unimplemented) GetSensor(w http.ResponseWriter, r *http.Request, params GetSensorParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User registration
// (POST /user)
func (_ Unimplemented) PostUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user password
// (PUT /user)
func (_ Unimplemented) PutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user details
// (GET /user/{id})
func (_ Unimplemented) GetUserId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a wheel
// (POST /wheels)
func (_ Unimplemented) PostWheels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update wheel data
// (PUT /wheels)
func (_ Unimplemented) PutWheels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get wheel data
// (GET /wheels/{id})
func (_ Unimplemented) GetWheelsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuto operation middleware
func (siw *ServerInterfaceWrapper) PostAuto(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuto(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReport operation middleware
func (siw *ServerInterfaceWrapper) GetReport(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReportParams

	// ------------- Required query parameter "userId" -------------

	if paramValue := r.URL.Query().Get("userId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "userId"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "userId", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSensor operation middleware
func (siw *ServerInterfaceWrapper) GetSensor(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSensorParams

	// ------------- Required query parameter "wheelId" -------------

	if paramValue := r.URL.Query().Get("wheelId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "wheelId"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "wheelId", r.URL.Query(), &params.WheelId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "wheelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSensor(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUser operation middleware
func (siw *ServerInterfaceWrapper) PostUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutUser operation middleware
func (siw *ServerInterfaceWrapper) PutUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostWheels operation middleware
func (siw *ServerInterfaceWrapper) PostWheels(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostWheels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutWheels operation middleware
func (siw *ServerInterfaceWrapper) PutWheels(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutWheels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWheelsId operation middleware
func (siw *ServerInterfaceWrapper) GetWheelsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AuthorizationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWheelsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auto", wrapper.PostAuto)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.PostLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/refresh", wrapper.PostRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/report", wrapper.GetReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sensor", wrapper.GetSensor)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/user", wrapper.PostUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/user", wrapper.PutUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user/{id}", wrapper.GetUserId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wheels", wrapper.PostWheels)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/wheels", wrapper.PutWheels)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wheels/{id}", wrapper.GetWheelsId)
	})

	return r
}

type PostAutoRequestObject struct {
	Body *PostAutoJSONRequestBody
}

type PostAutoResponseObject interface {
	VisitPostAutoResponse(w http.ResponseWriter) error
}

type PostAuto200JSONResponse VehicleResponse

func (response PostAuto200JSONResponse) VisitPostAutoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostLoginRequestObject struct {
	Body *PostLoginJSONRequestBody
}

type PostLoginResponseObject interface {
	VisitPostLoginResponse(w http.ResponseWriter) error
}

type PostLogin200JSONResponse TokenResponse

func (response PostLogin200JSONResponse) VisitPostLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRefreshRequestObject struct {
}

type PostRefreshResponseObject interface {
	VisitPostRefreshResponse(w http.ResponseWriter) error
}

type PostRefresh200JSONResponse TokenResponse

func (response PostRefresh200JSONResponse) VisitPostRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReportRequestObject struct {
	Params GetReportParams
}

type GetReportResponseObject interface {
	VisitGetReportResponse(w http.ResponseWriter) error
}

type GetReport200ApplicationvndOpenxmlformatsOfficedocumentSpreadsheetmlSheetResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetReport200ApplicationvndOpenxmlformatsOfficedocumentSpreadsheetmlSheetResponse) VisitGetReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetSensorRequestObject struct {
	Params GetSensorParams
}

type GetSensorResponseObject interface {
	VisitGetSensorResponse(w http.ResponseWriter) error
}

type GetSensor200JSONResponse SensorData

func (response GetSensor200JSONResponse) VisitGetSensorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostUserRequestObject struct {
	Body *PostUserJSONRequestBody
}

type PostUserResponseObject interface {
	VisitPostUserResponse(w http.ResponseWriter) error
}

type PostUser200Response struct {
}

func (response PostUser200Response) VisitPostUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutUserRequestObject struct {
	Body *PutUserJSONRequestBody
}

type PutUserResponseObject interface {
	VisitPutUserResponse(w http.ResponseWriter) error
}

type PutUser200Response struct {
}

func (response PutUser200Response) VisitPutUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetUserIdRequestObject struct {
	Id string `json:"id"`
}

type GetUserIdResponseObject interface {
	VisitGetUserIdResponse(w http.ResponseWriter) error
}

type GetUserId200JSONResponse UserDetails

func (response GetUserId200JSONResponse) VisitGetUserIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostWheelsRequestObject struct {
	Body *PostWheelsJSONRequestBody
}

type PostWheelsResponseObject interface {
	VisitPostWheelsResponse(w http.ResponseWriter) error
}

type PostWheels200JSONResponse WheelResponse

func (response PostWheels200JSONResponse) VisitPostWheelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutWheelsRequestObject struct {
	Body *PutWheelsJSONRequestBody
}

type PutWheelsResponseObject interface {
	VisitPutWheelsResponse(w http.ResponseWriter) error
}

type PutWheels200JSONResponse WheelResponse

func (response PutWheels200JSONResponse) VisitPutWheelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWheelsIdRequestObject struct {
	Id string `json:"id"`
}

type GetWheelsIdResponseObject interface {
	VisitGetWheelsIdResponse(w http.ResponseWriter) error
}

type GetWheelsId200JSONResponse WheelResponse

func (response GetWheelsId200JSONResponse) VisitGetWheelsIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register a vehicle
	// (POST /auto)
	PostAuto(ctx context.Context, request PostAutoRequestObject) (PostAutoResponseObject, error)
	// User login
	// (POST /login)
	PostLogin(ctx context.Context, request PostLoginRequestObject) (PostLoginResponseObject, error)
	// Refresh access token
	// (POST /refresh)
	PostRefresh(ctx context.Context, request PostRefreshRequestObject) (PostRefreshResponseObject, error)
	// Generate report
	// (GET /report)
	GetReport(ctx context.Context, request GetReportRequestObject) (GetReportResponseObject, error)
	// Get sensor data
	// (GET /sensor)
	GetSensor(ctx context.Context, request GetSensorRequestObject) (GetSensorResponseObject, error)
	// User registration
	// (POST /user)
	PostUser(ctx context.Context, request PostUserRequestObject) (PostUserResponseObject, error)
	// Update user password
	// (PUT /user)
	PutUser(ctx context.Context, request PutUserRequestObject) (PutUserResponseObject, error)
	// Get user details
	// (GET /user/{id})
	GetUserId(ctx context.Context, request GetUserIdRequestObject) (GetUserIdResponseObject, error)
	// Register a wheel
	// (POST /wheels)
	PostWheels(ctx context.Context, request PostWheelsRequestObject) (PostWheelsResponseObject, error)
	// Update wheel data
	// (PUT /wheels)
	PutWheels(ctx context.Context, request PutWheelsRequestObject) (PutWheelsResponseObject, error)
	// Get wheel data
	// (GET /wheels/{id})
	GetWheelsId(ctx context.Context, request GetWheelsIdRequestObject) (GetWheelsIdResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAuto operation middleware
func (sh *strictHandler) PostAuto(w http.ResponseWriter, r *http.Request) {
	var request PostAutoRequestObject

	var body PostAutoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuto(ctx, request.(PostAutoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuto")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAutoResponseObject); ok {
		if err := validResponse.VisitPostAutoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLogin operation middleware
func (sh *strictHandler) PostLogin(w http.ResponseWriter, r *http.Request) {
	var request PostLoginRequestObject

	var body PostLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogin(ctx, request.(PostLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLoginResponseObject); ok {
		if err := validResponse.VisitPostLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRefresh operation middleware
func (sh *strictHandler) PostRefresh(w http.ResponseWriter, r *http.Request) {
	var request PostRefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRefresh(ctx, request.(PostRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRefreshResponseObject); ok {
		if err := validResponse.VisitPostRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReport operation middleware
func (sh *strictHandler) GetReport(w http.ResponseWriter, r *http.Request, params GetReportParams) {
	var request GetReportRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReport(ctx, request.(GetReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReportResponseObject); ok {
		if err := validResponse.VisitGetReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSensor operation middleware
func (sh *strictHandler) GetSensor(w http.ResponseWriter, r *http.Request, params GetSensorParams) {
	var request GetSensorRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSensor(ctx, request.(GetSensorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSensor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSensorResponseObject); ok {
		if err := validResponse.VisitGetSensorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostUser operation middleware
func (sh *strictHandler) PostUser(w http.ResponseWriter, r *http.Request) {
	var request PostUserRequestObject

	var body PostUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostUser(ctx, request.(PostUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostUserResponseObject); ok {
		if err := validResponse.VisitPostUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutUser operation middleware
func (sh *strictHandler) PutUser(w http.ResponseWriter, r *http.Request) {
	var request PutUserRequestObject

	var body PutUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutUser(ctx, request.(PutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutUserResponseObject); ok {
		if err := validResponse.VisitPutUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserId operation middleware
func (sh *strictHandler) GetUserId(w http.ResponseWriter, r *http.Request, id string) {
	var request GetUserIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserId(ctx, request.(GetUserIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserIdResponseObject); ok {
		if err := validResponse.VisitGetUserIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostWheels operation middleware
func (sh *strictHandler) PostWheels(w http.ResponseWriter, r *http.Request) {
	var request PostWheelsRequestObject

	var body PostWheelsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostWheels(ctx, request.(PostWheelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostWheels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostWheelsResponseObject); ok {
		if err := validResponse.VisitPostWheelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutWheels operation middleware
func (sh *strictHandler) PutWheels(w http.ResponseWriter, r *http.Request) {
	var request PutWheelsRequestObject

	var body PutWheelsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutWheels(ctx, request.(PutWheelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutWheels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutWheelsResponseObject); ok {
		if err := validResponse.VisitPutWheelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWheelsId operation middleware
func (sh *strictHandler) GetWheelsId(w http.ResponseWriter, r *http.Request, id string) {
	var request GetWheelsIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWheelsId(ctx, request.(GetWheelsIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWheelsId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWheelsIdResponseObject); ok {
		if err := validResponse.VisitGetWheelsIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
